### ISSUE TITLE
No access to this project or group

### ISSUE THREAD

**Issue by misterhtmlcss** [software-developers-of-calgary/groupsite#22]
Can we make things more open? I can't even see the Project board that @venetrius created. I know no one is trying to 'protect' the code, so more openness my make it easier to get people involved. 

Thoughts?

**Comment by misterhtmlcss** [comment]
I can't add labels or even assign people e.g. this issue to Simon or Gergely or others. Just throwing ideas out there!

**Comment by venetrius** [comment]
@misterhtmlcss I could not find any setting to make it accessible outside of the organization. Sent you an invite.

**Comment by venetrius** [comment]
create new public project https://github.com/orgs/software-developers-of-calgary/projects/1, the board is visible and quite empty.
Can I close this issue?

**Comment by misterhtmlcss** [comment]
Yes no problem. Thank you.
